### ISSUE TITLE
Stock at starting the bot

### ISSUE THREAD

**Issue by bassel999** [ifeelscam/Instagram-Report-bot#4]
Hi,

Can you please help with setting up the api token for the telegram bot
 python main.py          
 * Serving Flask app 'main'
 * Debug mode: off
Starting the bot...

is those look correct, if you can please add some instruction on how we can get those keys it will be grea, becouse telgram have bot key app key, and I was not able to figer our where I can get the "FORCE_JOIN_CHANNEL"
```
API_TOKEN = os.getenv("3bce3aa3543d47f80962465ddbeeXXX")
FORCE_JOIN_CHANNEL = os.getenv("asd14123123)
ADMIN_ID = os.getenv("15371XXXX")

bot = telebot.TeleBot("7922558201:AAErAeDSJzKvAy71wxq2L1lhGvFZLQXXXX")
```

**Comment by ifeelscam** [comment]
Bro don't any changes with **main.py**  

I have already provided only file for all these things 
File name **.env**

**Comment by bassel999** [comment]
Hi,
I'm trying to deploy it using koyeb.com, and I added all the environment variables except for DATABASE_URL,
I deployed a database service on koyeb but I can't figer it out, can you please help even if it paid

**Comment by ifeelscam** [comment]
Use HEROKU
